-   id: check-commit-msg
    name: Check commit message
    description: "Ensure commit messages follow required format."
    entry: '^JIRA-\d+ - .+$'
    language: pygrep
    stages: [commit-msg]
    args: [--negate]