-   id: check-commit-msg
    name: Check commit message
    description: Checks commit messages for conformance to a specified format.
    entry: check-commit-msg
    language: python
    types: [python]
    stages: [commit-msg]