-   id: check-commit-msg
    name: Check commit message
    description: "Ensure commit messages follow required format."
    entry: '^JIRA-\d+ - .+$'
    language: pygrep
    types: [text]
    stages: [commit-msg]